version: "3.9"
services:
  mysql:
    image: mysql:5.7
    restart: on-failure
    volumes:
      - mysqlData:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=gbs
      - MYSQL_PASSWORD=-gbs-
  
  wp:
    image: wordpress
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - 8080:80
    volumes:
      - wpData:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=gbs
      - WORDPRESS_DB_PASSWORD=-gbs-
      - WORDPRESS_DB_NAME=wordpress

volumes:
  mysqlData:
  wpData:
